# Use the official PHP image as the base image
FROM php:8.1.0-apache

# Install required extensions and dependencies
RUN apt-get update && apt-get install -y \
    libzip-dev \
    unzip \
    && docker-php-ext-install zip pdo_mysql

# Set the working directory in the container
WORKDIR /var/www/html

# Copy composer.json and composer.lock to install dependencies
COPY ./composer.json  ./
COPY .env .env
COPY ./composer.lock  ./

# Install composer dependencies
# Descargar e instalar Composer 2.1.9
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=2.5.8



# Copy the rest of the application code
COPY . .

RUN composer update
RUN composer install

# Generate the optimized autoloader and clear the cache
RUN composer dump-autoload --optimize

# Set permissions for storage and bootstrap cache
RUN chown -R www-data:www-data storage bootstrap/cache

# Expose port 80 for Apache
EXPOSE 80

# Start Apache in the foreground
CMD ["apache2-foreground"]
